ALTER TABLE `access_keys` CHANGE `context` `context` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `access_keys` CHANGE `key_hash` `key_hash` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `announcement_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `announcement_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `announcement_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `announcement_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `announcement_type_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `announcement_type_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `announcement_type_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `announcement_type_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `article_galley_settings` CHANGE `locale` `locale` varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `article_galley_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `article_galley_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `article_galley_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `article_supp_file_settings` CHANGE `locale` `locale` varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `article_supp_file_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `article_supp_file_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `article_supp_file_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `article_supplementary_files` CHANGE `type` `type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `article_supplementary_files` CHANGE `language` `language` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `article_supplementary_files` CHANGE `remote_url` `remote_url` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `auth_sources` CHANGE `title` `title` varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `auth_sources` CHANGE `plugin` `plugin` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `auth_sources` CHANGE `settings` `settings` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `author_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `author_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `author_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `author_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `authors` CHANGE `country` `country` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `authors` CHANGE `email` `email` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `authors` CHANGE `url` `url` varchar(2047) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `books_for_review` CHANGE `publisher` `publisher` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `books_for_review` CHANGE `language` `language` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'en';
ALTER TABLE `books_for_review` CHANGE `url` `url` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `books_for_review` CHANGE `isbn` `isbn` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `books_for_review` CHANGE `notes` `notes` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `books_for_review_authors` CHANGE `first_name` `first_name` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `books_for_review_authors` CHANGE `middle_name` `middle_name` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `books_for_review_authors` CHANGE `last_name` `last_name` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `books_for_review_settings` CHANGE `locale` `locale` varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `books_for_review_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `books_for_review_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `books_for_review_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `captchas` CHANGE `session_id` `session_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `captchas` CHANGE `value` `value` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `citation_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `citation_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `citation_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `citation_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `citations` CHANGE `raw_citation` `raw_citation` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `comments` CHANGE `poster_ip` `poster_ip` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `comments` CHANGE `poster_name` `poster_name` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `comments` CHANGE `poster_email` `poster_email` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `comments` CHANGE `title` `title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `comments` CHANGE `body` `body` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `completed_payments` CHANGE `currency_code_alpha` `currency_code_alpha` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `completed_payments` CHANGE `payment_method_plugin_name` `payment_method_plugin_name` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `controlled_vocabs` CHANGE `symbolic` `symbolic` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `data_object_tombstone_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `data_object_tombstone_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `data_object_tombstone_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `data_object_tombstone_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `data_object_tombstones` CHANGE `set_spec` `set_spec` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `data_object_tombstones` CHANGE `set_name` `set_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `data_object_tombstones` CHANGE `oai_identifier` `oai_identifier` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `dataverse_files` CHANGE `content_source_uri` `content_source_uri` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `dataverse_studies` CHANGE `edit_uri` `edit_uri` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `dataverse_studies` CHANGE `edit_media_uri` `edit_media_uri` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `dataverse_studies` CHANGE `statement_uri` `statement_uri` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `dataverse_studies` CHANGE `persistent_uri` `persistent_uri` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `dataverse_studies` CHANGE `data_citation` `data_citation` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `email_log` CHANGE `ip_address` `ip_address` varchar(39) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `email_log` CHANGE `from_address` `from_address` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `email_log` CHANGE `recipients` `recipients` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `email_log` CHANGE `cc_recipients` `cc_recipients` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `email_log` CHANGE `bcc_recipients` `bcc_recipients` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `email_log` CHANGE `subject` `subject` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `email_log` CHANGE `body` `body` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `email_templates` CHANGE `email_key` `email_key` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `email_templates_data` CHANGE `email_key` `email_key` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `email_templates_data` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'en_US';
ALTER TABLE `email_templates_data` CHANGE `subject` `subject` varchar(120) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `email_templates_data` CHANGE `body` `body` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `email_templates_default` CHANGE `email_key` `email_key` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `email_templates_default_data` CHANGE `email_key` `email_key` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `email_templates_default_data` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'en_US';
ALTER TABLE `email_templates_default_data` CHANGE `subject` `subject` varchar(120) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `email_templates_default_data` CHANGE `body` `body` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `email_templates_default_data` CHANGE `description` `description` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `event_log` CHANGE `ip_address` `ip_address` varchar(39) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `event_log` CHANGE `message` `message` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `event_log_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `event_log_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `event_log_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `external_feed_settings` CHANGE `locale` `locale` varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `external_feed_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `external_feed_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `external_feed_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `external_feeds` CHANGE `url` `url` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `filter_groups` CHANGE `symbolic` `symbolic` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `filter_groups` CHANGE `display_name` `display_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `filter_groups` CHANGE `description` `description` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `filter_groups` CHANGE `input_type` `input_type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `filter_groups` CHANGE `output_type` `output_type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `filter_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `filter_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `filter_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `filter_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `filters` CHANGE `display_name` `display_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `filters` CHANGE `class_name` `class_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `gifts` CHANGE `buyer_first_name` `buyer_first_name` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `gifts` CHANGE `buyer_middle_name` `buyer_middle_name` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `gifts` CHANGE `buyer_last_name` `buyer_last_name` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `gifts` CHANGE `buyer_email` `buyer_email` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `gifts` CHANGE `recipient_first_name` `recipient_first_name` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `gifts` CHANGE `recipient_middle_name` `recipient_middle_name` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `gifts` CHANGE `recipient_last_name` `recipient_last_name` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `gifts` CHANGE `recipient_email` `recipient_email` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `gifts` CHANGE `locale` `locale` varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `gifts` CHANGE `gift_note_title` `gift_note_title` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `gifts` CHANGE `gift_note` `gift_note` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `gifts` CHANGE `notes` `notes` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `group_settings` CHANGE `locale` `locale` varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `group_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `group_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `group_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `institutional_subscription_ip` CHANGE `ip_string` `ip_string` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `institutional_subscriptions` CHANGE `institution_name` `institution_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `institutional_subscriptions` CHANGE `mailing_address` `mailing_address` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `institutional_subscriptions` CHANGE `domain` `domain` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `issue_files` CHANGE `file_name` `file_name` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `issue_files` CHANGE `file_type` `file_type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `issue_files` CHANGE `original_file_name` `original_file_name` varchar(127) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `issue_galley_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `issue_galley_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `issue_galley_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `issue_galley_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `issue_galleys` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `issue_galleys` CHANGE `label` `label` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `issue_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `issue_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `issue_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `issue_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `issues` CHANGE `number` `number` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `issues` CHANGE `style_file_name` `style_file_name` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `issues` CHANGE `original_style_file_name` `original_style_file_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `journal_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `journal_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `journal_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `journal_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `journals` CHANGE `path` `path` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `journals` CHANGE `primary_locale` `primary_locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `metadata_description_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `metadata_description_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `metadata_description_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `metadata_description_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `metadata_descriptions` CHANGE `schema_namespace` `schema_namespace` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `metadata_descriptions` CHANGE `schema_name` `schema_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `metadata_descriptions` CHANGE `display_name` `display_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `metrics` CHANGE `load_id` `load_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `metrics` CHANGE `day` `day` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `metrics` CHANGE `month` `month` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `metrics` CHANGE `country_id` `country_id` varchar(2) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `metrics` CHANGE `region` `region` varchar(2) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `metrics` CHANGE `city` `city` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `metrics` CHANGE `metric_type` `metric_type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `notes` CHANGE `title` `title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `notes` CHANGE `contents` `contents` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `notification_mail_list` CHANGE `email` `email` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `notification_mail_list` CHANGE `token` `token` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `notification_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `notification_settings` CHANGE `setting_name` `setting_name` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `notification_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `notification_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `notification_subscription_settings` CHANGE `setting_name` `setting_name` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `notification_subscription_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `notification_subscription_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `oai_resumption_tokens` CHANGE `token` `token` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `oai_resumption_tokens` CHANGE `params` `params` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `object_for_review_assignments` CHANGE `notes` `notes` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `object_for_review_persons` CHANGE `role` `role` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `object_for_review_persons` CHANGE `first_name` `first_name` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `object_for_review_persons` CHANGE `middle_name` `middle_name` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `object_for_review_persons` CHANGE `last_name` `last_name` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `object_for_review_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `object_for_review_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `objects_for_review` CHANGE `notes` `notes` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `paypal_transactions` CHANGE `txn_id` `txn_id` varchar(17) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `paypal_transactions` CHANGE `txn_type` `txn_type` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `paypal_transactions` CHANGE `payer_email` `payer_email` varchar(127) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `paypal_transactions` CHANGE `receiver_email` `receiver_email` varchar(127) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `paypal_transactions` CHANGE `item_number` `item_number` varchar(127) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `paypal_transactions` CHANGE `payment_date` `payment_date` varchar(127) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `paypal_transactions` CHANGE `payer_id` `payer_id` varchar(13) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `paypal_transactions` CHANGE `receiver_id` `receiver_id` varchar(13) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `pln_deposit_objects` CHANGE `object_type` `object_type` varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `pln_deposits` CHANGE `uuid` `uuid` varchar(36) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `plugin_settings` CHANGE `plugin_name` `plugin_name` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `plugin_settings` CHANGE `setting_name` `setting_name` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `plugin_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `plugin_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `processes` CHANGE `process_id` `process_id` varchar(23) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `queued_payments` CHANGE `payment_data` `payment_data` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `referral_settings` CHANGE `locale` `locale` varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `referral_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `referral_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `referral_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `referrals` CHANGE `url` `url` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `review_assignments` CHANGE `competing_interests` `competing_interests` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `review_form_element_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `review_form_element_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `review_form_element_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `review_form_element_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `review_form_responses` CHANGE `response_type` `response_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `review_form_responses` CHANGE `response_value` `response_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `review_form_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `review_form_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `review_form_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `review_form_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `review_object_metadata` CHANGE `metadata_key` `metadata_key` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `review_object_type_settings` CHANGE `locale` `locale` varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `review_object_type_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `review_object_type_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `review_object_type_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `review_object_types` CHANGE `type_key` `type_key` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `rt_contexts` CHANGE `title` `title` varchar(120) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `rt_contexts` CHANGE `abbrev` `abbrev` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `rt_contexts` CHANGE `description` `description` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `rt_searches` CHANGE `title` `title` varchar(120) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `rt_searches` CHANGE `description` `description` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `rt_searches` CHANGE `url` `url` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `rt_searches` CHANGE `search_url` `search_url` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `rt_searches` CHANGE `search_post` `search_post` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `rt_versions` CHANGE `version_key` `version_key` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `rt_versions` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'en_US';
ALTER TABLE `rt_versions` CHANGE `title` `title` varchar(120) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `rt_versions` CHANGE `description` `description` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `scheduled_tasks` CHANGE `class_name` `class_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `section_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `section_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `section_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `section_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `sessions` CHANGE `session_id` `session_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `sessions` CHANGE `ip_address` `ip_address` varchar(39) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `sessions` CHANGE `user_agent` `user_agent` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `sessions` CHANGE `data` `data` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `sessions` CHANGE `domain` `domain` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `signoffs` CHANGE `symbolic` `symbolic` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `site` CHANGE `primary_locale` `primary_locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `site` CHANGE `installed_locales` `installed_locales` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'en_US';
ALTER TABLE `site` CHANGE `supported_locales` `supported_locales` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `site` CHANGE `original_style_file_name` `original_style_file_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `site_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `site_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `site_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `site_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `static_page_settings` CHANGE `locale` `locale` varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `static_page_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `static_page_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `static_pages` CHANGE `path` `path` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `subscription_type_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `subscription_type_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `subscription_type_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `subscription_type_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `subscription_types` CHANGE `currency_code_alpha` `currency_code_alpha` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `subscriptions` CHANGE `membership` `membership` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `subscriptions` CHANGE `reference_number` `reference_number` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `subscriptions` CHANGE `notes` `notes` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `temporary_files` CHANGE `file_name` `file_name` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `temporary_files` CHANGE `file_type` `file_type` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `temporary_files` CHANGE `original_file_name` `original_file_name` varchar(127) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `theses` CHANGE `degree_name` `degree_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `theses` CHANGE `department` `department` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `theses` CHANGE `university` `university` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `theses` CHANGE `title` `title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `theses` CHANGE `url` `url` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `theses` CHANGE `abstract` `abstract` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `theses` CHANGE `comment` `comment` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `theses` CHANGE `student_first_name` `student_first_name` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `theses` CHANGE `student_middle_name` `student_middle_name` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `theses` CHANGE `student_last_name` `student_last_name` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `theses` CHANGE `student_email` `student_email` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `theses` CHANGE `student_bio` `student_bio` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `theses` CHANGE `supervisor_first_name` `supervisor_first_name` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `theses` CHANGE `supervisor_middle_name` `supervisor_middle_name` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `theses` CHANGE `supervisor_last_name` `supervisor_last_name` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `theses` CHANGE `supervisor_email` `supervisor_email` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `theses` CHANGE `discipline` `discipline` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `theses` CHANGE `subject_class` `subject_class` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `theses` CHANGE `subject` `subject` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `theses` CHANGE `coverage_geo` `coverage_geo` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `theses` CHANGE `coverage_chron` `coverage_chron` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `theses` CHANGE `coverage_sample` `coverage_sample` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `theses` CHANGE `method` `method` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `theses` CHANGE `language` `language` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'en';
ALTER TABLE `usage_stats_temporary_records` CHANGE `country_id` `country_id` varchar(2) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `usage_stats_temporary_records` CHANGE `region` `region` varchar(2) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `usage_stats_temporary_records` CHANGE `city` `city` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `usage_stats_temporary_records` CHANGE `load_id` `load_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `user_settings` CHANGE `locale` `locale` varchar(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `user_settings` CHANGE `setting_name` `setting_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `user_settings` CHANGE `setting_value` `setting_value` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `user_settings` CHANGE `setting_type` `setting_type` varchar(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `users` CHANGE `username` `username` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `users` CHANGE `password` `password` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `users` CHANGE `email` `email` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `users` CHANGE `url` `url` varchar(2047) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `users` CHANGE `phone` `phone` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `users` CHANGE `mailing_address` `mailing_address` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `users` CHANGE `billing_address` `billing_address` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `users` CHANGE `country` `country` varchar(90) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `users` CHANGE `locales` `locales` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `users` CHANGE `auth_str` `auth_str` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `users` CHANGE `disabled_reason` `disabled_reason` text CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `versions` CHANGE `product_type` `product_type` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `versions` CHANGE `product` `product` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
ALTER TABLE `versions` CHANGE `product_class_name` `product_class_name` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
